// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-99RTq5sAekX9Wk7MDgNREuJhdhnFFck',
    appId: '1:157218488338:web:bf7e7a5b50cb7fa69c58cb',
    messagingSenderId: '157218488338',
    projectId: 'recruito-5c9e3',
    authDomain: 'recruito-5c9e3.firebaseapp.com',
    storageBucket: 'recruito-5c9e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjwOW4RafhGk_MwEtW9Obsi9MAQeP8ALU',
    appId: '1:157218488338:android:32197988a43f28419c58cb',
    messagingSenderId: '157218488338',
    projectId: 'recruito-5c9e3',
    storageBucket: 'recruito-5c9e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-to0JBmf2I1yf0Ur222rhCbegBdX4AhM',
    appId: '1:157218488338:ios:6155098dce3fc65e9c58cb',
    messagingSenderId: '157218488338',
    projectId: 'recruito-5c9e3',
    storageBucket: 'recruito-5c9e3.appspot.com',
    iosBundleId: 'com.example.collegeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-to0JBmf2I1yf0Ur222rhCbegBdX4AhM',
    appId: '1:157218488338:ios:4c5a9358ff1048ac9c58cb',
    messagingSenderId: '157218488338',
    projectId: 'recruito-5c9e3',
    storageBucket: 'recruito-5c9e3.appspot.com',
    iosBundleId: 'com.example.collegeProject.RunnerTests',
  );
}
